- name: Remote
  slug: remote
  width: wide
  columns:
    - size: full
      widgets:
        - type: html
          title: Remote
          title-url: http://${HOST_SVC}:8080
          source: |
            <div data-wb="remote-workspace" data-wb-noindex></div>
