#!/usr/bin/env python3
"""Writes /opt/glance/glance.env: ONLY the variables that Glance's own config references (${VAR} in config/*.yml, pages/*.yml, data/*.yml).

/opt/glance/.env stays the master file (host addresses + every secret, including the ones only glance-admin uses).
The Glance container reads glance.env, so it never receives secrets it does not need.
Run after adding or removing a ${VAR} in the config, then: cd /opt/stacks/glance && docker compose up -d   (env is read at container creation)
"""
import glob
import os
import re

MASTER, OUT = "/opt/glance/.env", "/opt/glance/glance.env"
master = {}
for line in open(MASTER, encoding="utf-8").read().splitlines():
    if "=" in line and not line.lstrip().startswith("#"):
        k, v = line.split("=", 1)
        master[k.strip()] = v
used = set()
for pat in ("/opt/glance/config/*.yml", "/opt/glance/config/pages/*.yml", "/opt/glance/config/data/*.yml"):
    for f in glob.glob(pat):
        used |= set(re.findall(r"\$\{([A-Za-z0-9_]+)\}", open(f, encoding="utf-8").read()))
missing = sorted(v for v in used if v not in master)
if missing:
    raise SystemExit("undefined in .env: %s" % ", ".join(missing))
lines = ["# generated by /opt/glance/tools/sync_env.py from .env: only the variables Glance's config uses. Do not edit."]
lines += ["%s=%s" % (k, master[k]) for k in sorted(used)]
tmp = OUT + ".tmp"
with open(tmp, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
os.chmod(tmp, 0o600)
os.replace(tmp, OUT)
print("wrote %s with %d variables (master has %d)" % (OUT, len(used), len(master)))
