#!/usr/bin/env python3
"""Writes the lock configuration for the PIN-locked widgets.

    python3 scripts/make_pin_config.py [PIN] > /opt/glance/assets/glance/wb-restricted-config.js

With no argument it reads GLANCE_PIN from /opt/glance/.env (or $GLANCE_PIN). The browser only ever receives a random salt and
SHA-256(salt + PIN); the PIN is not in the page. This is casual privacy (it keeps a visitor or a glance over your shoulder out), not
security: the locked widgets' data is still in the page source.
"""
import hashlib
import os
import secrets
import sys


def pin_from_env():
    if os.environ.get("GLANCE_PIN"):
        return os.environ["GLANCE_PIN"]
    for path in ("/opt/glance/.env", ".env"):
        try:
            for line in open(path, encoding="utf-8"):
                if line.startswith("GLANCE_PIN="):
                    return line.split("=", 1)[1].strip().strip('"').strip("'")
        except OSError:
            continue
    return ""


def make(pin):
    salt = secrets.token_hex(16)
    return salt, hashlib.sha256((salt + pin).encode("utf-8")).hexdigest()


if __name__ == "__main__":
    pin = sys.argv[1] if len(sys.argv) > 1 else pin_from_env()
    if not pin:
        sys.exit("no PIN: pass it as an argument or set GLANCE_PIN in /opt/glance/.env")
    salt, digest = make(pin)
    print("/* generated by scripts/make_pin_config.py: salted SHA-256 of the restricted-row PIN */")
    print('window.WB_RESTRICTED = {salt: "%s", hash: "%s"};' % (salt, digest))
